common_path_base: C:/Users/Husse/Documents/TER/TERCompletionNuages/
dataset:
  name: Arabidopsis
  category_file_path: /kaggle/working/TER/completion/category_files/Arabidopsis.json
  partial_points_path: /kaggle/input/partialpointcloud/partial/%s
  complete_points_path: /kaggle/input/partialpointcloud/partial/%s
  n_renderings: 8
  n_points: 2048

model:
  dim_feat: 512
  up_factors: [1, 4, 8]
  num_pc: 256
  num_p0: 512
  bounding: True
  radius: 1.0

train:
  optimizer: {
    type: Adam,
    kwargs: {
      lr: 0.001,
      weight_decay: 0.0005,
      betas: [.9, .999]
    },
    decay_factor: 2,
    decay_freq: 10,
    decay_ignore: 210,
    }
  scheduler: {
    type: StepLR,
    kwargs: {
      decay_step: 50,
      gamma: 0.5,
    }}
  seed: 2022
  gpu: [0, 1]
  batch_size: 12
  num_workers: 2
  epochs: 400
  loss_func: cd_l2
  betas: [.9, .999]
  init_epoch: 1
  save_freq: 2
  split_freq: 15
  out_path:
  resume: True
  #model_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/experiments/ckpt-best.pth
  model_path: /kaggle/working/TER/completion/exp/best/ckpt-best.pth
#  updated_model_reader: D:/M1/S2/TER/Train/SnowflakeNet/completion/configs/train_update.yaml

test:
  split: test
  gpu: [0, 1]
  batch_size: 8
  num_workers: 2
  loss_func: cd_l2
  #model_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/experiments/ckpt-best.pth
  model_path: /kaggle/working/TER/completion/exp/best/ckpt-best.pth

