common_path_base: C:/Users/Husse/Documents/TER/TERCompletionNuages/
dataset:
  name: Arabidopsis
  category_file_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/completion/category_files/Arabidopsis.json
  partial_points_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/data/Arabidopsis/partial/%s
  complete_points_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/data/Arabidopsis/complete/%s
  n_renderings: 8
  n_points: 2048

model:
  dim_feat: 512
  up_factors: [1, 4, 8]
  num_pc: 256
  num_p0: 512
  bounding: True
  radius: 1.0

train:
  optimizer: {
    type: Adam,
    kwargs: {
      lr: 0.001,
      weight_decay: 0,
      betas: [.9, .999]
    }}
  scheduler: {
    type: StepLR,
    kwargs: {
      decay_step: 50,
      gamma: 0.5,
    }}
  seed: 2022
  gpu: [0]
  batch_size: 4
  num_workers: 4
  epochs: 50
  loss_func: cd_l2
  betas: [.9, .999]
  init_epoch: 1
  save_freq: 1
  split_freq: 5
  out_path:
  resume: True
  model_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/experiments/ckpt-best.pth
#  updated_model_reader: D:/M1/S2/TER/Train/SnowflakeNet/completion/configs/train_update.yaml

test:
  split: test
  gpu: [0]
  batch_size: 4
  num_workers: 4
  loss_func: cd_l2
  model_path: C:/Users/Husse/Documents/TER/TERCompletionNuages/experiments/ckpt-best.pth